### 1. Write a Python Program to Add two Matrices ?

In [1]:
import numpy as np
def add_matrices(a,b):
    if len(a)==len(b):
        for ele in range(len(a)):
            if len(a[ele])==len(b[ele]):
                output = np.array(a)+np.array(b)
        return output        

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2,3],[4,5,6],[7,8,9]]
print(add_matrices(a,b))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### 2. Write a Python Program to Multiply two Matrices ?

In [2]:
import numpy as np
def multiply_matrices(a,b):
    if len(a)==len(b):
        for ele in range(len(a)):
            if len(a[ele])==len(b[ele]):
                output = np.array(a)*np.array(b)
        return output        

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[1,2,3],[4,5,6],[7,8,9]]
print(multiply_matrices(a,b)) 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 3. Write a Python Program to transpose a Matrix ?

In [3]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]
matrix2 = [[1, 2, 3], [4, 5, 6]]
def trans_matrix(a):
    l=[]
    for j in range(len(a[0])):
        l1=[]
        for i in range(len(a)):
            l1.append(a[i][j])
        l.append(l1)
    return f'Before transpose {a} , After transpose {l}'   

print(trans_matrix(matrix1))
print(trans_matrix(matrix2))

Before transpose [[1, 2, 3], [4, 5, 6], [7, 8, 9]] , After transpose [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
Before transpose [[1, 2, 3], [4, 5, 6]] , After transpose [[1, 4], [2, 5], [3, 6]]


### 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [4]:
string = 'full stack data science'
def sort_string(s):
    string = sorted(s.title().split(' '))
    return string

sort_string(string)

['Data', 'Full', 'Science', 'Stack']

### 5. Write a Python Program to remove Punctuations From a String ?

In [6]:
def remove_Punc():
    punctuation = '''!"#$%&'()*,-./:;<>?@[\]^_`|{}~'''
    string = input("enter string ")
    final_string = ''
    for i in string:
        if i not in punctuation:
            final_string += i
    print(final_string)
    
remove_Punc()

enter string "Hey, Budy:,' !, How are you?"
Hey Budy  How are you
